<?php include 'header.php'; ?>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">


<main class="dashboard-bg">

    <!-- Top-left RIRAF -->
<div class="riraf-table-header">
    <div class="riraf-top-left">RIRAF</div>

    <div class="riraf-search">
        <label for="dateSearch">Search Date:</label>
        <input type="date" id="dateSearch" placeholder="mm/dd/yyyy">
    </div>
</div>

    <!-- Table container -->
    <div class="riraf-table-wrapper">

        <!-- Top-middle title + Search -->
    <div class="riraf-table-header">
        <div class="riraf-center">RIRAF RECORDS</div>
    </div>


        <!-- Table -->
        <table class="riraf-table" id="rirafTable">
            <thead>
                <tr>
                    <th>Province</th>
                    <th>Location</th>
                    <th>File Name</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="tableBody">
                <!-- Empty rows will be generated by JS -->
            </tbody>
        </table>

        <!-- Pagination -->
        <div class="pagination">
            <button id="prevBtn"><i class="fa-solid fa-arrow-left"></i> Previous</button>
            <button id="nextBtn">Next <i class="fa-solid fa-arrow-right"></i></button>
        </div>


    </div>

</main>

<script>
// Pagination + empty rows + Action buttons
const totalRows = 29;
const rowsPerPage = 13;
let currentPage = 1;

    function renderTable() {
        const tbody = document.getElementById('tableBody');
            tbody.innerHTML = '';

        const start = (currentPage - 1) * rowsPerPage;
        const end = Math.min(start + rowsPerPage, totalRows);

        for (let i = start; i < end; i++) {
            const tr = document.createElement('tr');

        // 4 empty columns
        for (let j = 0; j < 4; j++) {
            const td = document.createElement('td');
            td.textContent = '';
            tr.appendChild(td);
        }

        // Action column
        const actionTd = document.createElement('td');

        const editBtn = document.createElement('button');
            editBtn.className = 'riraf-edit-btn';
            editBtn.innerHTML = '<i class="fa-solid fa-pen"></i> Edit';
            editBtn.onclick = () => alert(`Edit row ${i + 1}`);

        const printBtn = document.createElement('button');
            printBtn.className = 'print-btn';
            printBtn.innerHTML = '<i class="fa-solid fa-print"></i> Print';
            printBtn.onclick = () => alert(`Print row ${i + 1}`);

            actionTd.appendChild(editBtn);
            actionTd.appendChild(printBtn);
            tr.appendChild(actionTd);

            tbody.appendChild(tr);
    }

    document.getElementById('prevBtn').disabled = currentPage === 1;
    document.getElementById('nextBtn').disabled = currentPage === Math.ceil(totalRows / rowsPerPage);
}

document.getElementById('prevBtn').addEventListener('click', () => {
    if (currentPage > 1) { currentPage--; renderTable(); }
});
document.getElementById('nextBtn').addEventListener('click', () => {
    if (currentPage < Math.ceil(totalRows / rowsPerPage)) { currentPage++; renderTable(); }
});

renderTable();
</script>
